### ISSUE TITLE
Sample Not tested.

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Delphi-Programming-Projects#1]
Sample not tested. It has a bug.

**Comment by williamjduarte** [comment]
Which chapter?

**Comment by ghost** [comment]
Chapter 1

**Comment by ghost** [comment]
I sent a pull request.
And Android Permission for 8.0.0 or higher was not considered

**Comment by williamjduarte** [comment]
Yes, the examples have not been made with Android 8, I can upload the change, if there is any doubt regarding permission in runtime, see:

Quick Example:

 

private

{$ IFDEF ANDROID}
   fReadStorage: = JStringToString (TJManifest_permission.JavaClass.READ_EXTERNAL_STORAGE);
   fWriteStorage: = JStringToString (TJManifest_permission.JavaClass.WRITE_EXTERNAL_STORAGE);
   fBlueTooth: = JStringToString (TJManifest_permission.JavaClass.BLUETOOTH);
{$ ENDIF}


procedure Tfrm ????. FormShow (Sender: TObject);
begin
{$ IF DEFINED (IOS) or DEFINED (ANDROID)}
PermissionsService.RequestPermissions ([fReadStorage, fWriteStorage, fBlueTooth], RequestPermissionsResult, DisplayRationale);
{$ ENDIF}
end;
