### ISSUE TITLE
Chapter 3 example does not work with Delphi 10.3.

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Delphi-Programming-Projects#3]
This example does not work with Delphi 10.3.
It is recommended that you refer to the samples that can be installed when you install the IDE in Chapter 3.

C:\Users\Public\Documents\Embarcadero\Studio\20.0\Samples\Object Pascal\Multi-Device Samples\Device Sensors and Services\AndroidNotificationServiceDemo

**Comment by AndreLuisCelestino** [comment]
Hi, Wayne!
Could you post the error message that you are getting when trying to reproduce this example?
I am not able to test it since I am already using 10.4.1 (Sydney).
